# Workflow for building and deploying pkgdown site to GitHub Pages
# For help, see: https://github.com/r-lib/actions/tree/v2/examples

name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only deploy on push events to main branch
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    permissions:
      contents: read
      pages: write
      id-token: write

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ./pkg
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Install CVXR specific version
        run: |
          remotes::install_version("CVXR", version = "0.99-7", repos = "http://cran.us.r-project.org")
        shell: Rscript {0}
        
      - name: Build site
        working-directory: ./pkg
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      # Deploy to GitHub pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        id: deployment
        uses: actions/deploy-pages@v2 